

version: '3'

services:
  
  website:
    image: node:18.15.0
    container_name: website
    restart: unless-stopped
    networks:
      website-network:
        ipv4_address: 192.168.10.2
    volumes:
      - ../:/var/www/backend
    command: bash -c "cd /var/www/backend && node index.js"

  caddy:
    depends_on:
      - website   
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    networks:
      website-network:
        ipv4_address: 192.168.10.3

#--------------------

networks:
    website-network:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1
