version: '3'

services:
  website:
    image: node:18.15.0
    container_name: website
    restart: unless-stopped
    depends_on:
      - db
    networks:
      website-network:
        ipv4_address: 192.168.10.2
    volumes:
      - ../:/var/www/backend
    command: bash -c "cd /var/www/backend && node index.js"

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      website-network:
        ipv4_address: 192.168.10.11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=C'
    volumes:
      - ./db/myDB.sql:/docker-entrypoint-initdb.d/fichier.sql
      - ./data/postgres:/var/lib/postgresql/data

  caddy:
    depends_on:
      - website
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    networks:
      website-network:
        ipv4_address: 192.168.10.3

#--------------------

networks:
  website-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
